project:
  type: website

website:
  title: "details"
  reader-mode: true
  repo-url: https://github.com/coatless-quarto/details/
  repo-actions: [edit, issue]
  sidebar:
    logo: "details-animated-logo.svg"
    logo-alt: "A hexagon logo for the details extension."
    style: "floating"
    search: true
    tools:
      - icon: github
        href: https://github.com/coatless-quarto/details/
    contents: 
      - text: "Home"
        file: index.qmd
      - section: "Support"
        contents:
        - text: "FAQ"
          href: qdetails-faq.qmd
        - text: "Submit an issue"
          href: https://github.com/coatless-quarto/details/issues/new/choose
      - section: "Extra"
        contents:
        - qdetails-release-notes.qmd

format: 
  html:
    toc: true